<?php
/**
 * @author Elsner Team
 * @copyright Copyright © Elsner Technologies Pvt. Ltd (https://www.elsner.com/)
 * @package Elsnertech_Paytrace
 */

/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */
?>

<?php
$methodCode = $block->escapeHtml($block->getMethodCode());
$savedCard = $block->getMethod()->getSavedCards();
?>
<fieldset class="fieldset items <?= /* @noEscape */ $methodCode ?>" 
    id="payment_form_<?= /* @noEscape */ $methodCode ?>" 
    style="display: none">
    <div class="field number required">
        <label for="paytracevault" class="label">
            <span><?= $block->escapeHtml(__('Saved Credit Card')) ?></span>
        </label>
        <div class="control">
            <?php if (!empty($savedCard)):?>
                <?php foreach ($savedCard as $item):?>
                    <div class="payment-method-title field choice">
                        <input type="radio" 
                        name="payment[paytrace_vault]" 
                        class="radio required-entry" 
                        data-id="<?= /* @noEscape */ $item['paytrace_customer_id']?>" 
                        value="<?= /* @noEscape */ $item['paytrace_customer_id']?>">
                        <label class="label" for="<?= /* @noEscape */ $item['paytrace_customer_id']?>">
                            <?php $imagePath = $item['card_image']; ?>
                            <img 
                            src="
                            <?= /* @noEscape */ $block->getViewFileUrl('Magento_Payment::images/cc/'.$imagePath); ?>" 
                            width="46" 
                            height="30" 
                            class="payment-icon">
                            <span ><?= /* @noEscape */ $item['last4']?></span>
                        </label>
                    </div>
                <?php endforeach;?>
            <?php endif;?>
        </div>
    </div>
    <input type="hidden" name="payment[captcha_string]" value="no-string"/>
</fieldset>
